name: build-test-deploy-workflow

on: workflow_dispatch

jobs:
  build-job:
    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run ls
        run: ls -la
  test-job:
    name: test
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "testing..."
  deploy-job:
    name: deploy
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploying..."