name: build-test-deploy-workflow

on: workflow_dispatch

jobs:
  build-job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check Docker version
        run: docker version
      - name: Build Docker image
        run: docker image build --tag marlonmoreira/battleships:latest .
      - name: List all images
        run: docker image ls
      - name: Log into DockerHub
        run: docker login -u marlonmoreira -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image to DockerHub
        run: docker image push marlonmoreira/battleships:latest
      - name: Logout of DockerHub
        run: docker logout
  test-job:
    name: test
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "testing..."
  deploy-job:
    name: deploy
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploying..."