name: build-test-deploy-workflow

on: workflow_dispatch

jobs:
  build-step:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "building..."
  test-step:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "testing..."
  deploy-step:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploying..."